version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "password-verify-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-qy1jltho1ncg"
s3_prefix = "password-verify-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
